### ISSUE TITLE
Add `getPublicKeyFromInput()` to `Transaction` class

### ISSUE THREAD

**Issue by theanmolsharma** [Bitshala-Incubator/silent-pay#11]
Add the following function to `Transaction` class
```js
getPublicKeyFromInput(index: number): Buffer | null {}
```

This function should extract the public key from the `script` or `witness` property of the input whichever is relevant based on the input type.
The following output script types contain public key in `script`:

- P2PKH

The following output script types contain public key in `witness`:

- P2WPKH
- P2SH-P2WPKH

For all other script types, the function should return `null`

**Comment by rajarshimaitra** [comment]
Same as the other one. How about Options? 

And also a doc of this behavior on the functions, explaining which one throws None and why.

**Comment by theanmolsharma** [comment]
> Same as the other one. How about Options?
> 
> And also a doc of this behavior on the functions, explaining which one throws None and why.

replied in #12
