### ISSUE TITLE
Use Yarn Workspaces (or Alternative) to make this a monorepo of separate packages

### ISSUE THREAD

**Issue by theanmolsharma** [Bitshala-Incubator/silent-pay#16]
We should use an alias for `src` directory instead of having '../../' in import paths.
I suggest we use something like `@core` and `@wallet` as aliases for importing core lib and wallet lib.

**Comment by emjshrx** [comment]
https://betterprogramming.pub/the-native-way-to-configure-path-aliases-in-frontend-projects-5db70f19a6e0

**Comment by emjshrx** [comment]
We need to migrate to something like yarn workspaces to manage the different folders as separate packages.

**Comment by theanmolsharma** [comment]
@emjshrx I've already started working on this and will open a PR by EOD today. I'll add you as a reviewer.
Sorry if you already spent time on this. I forgot to mention it here that I'm working on this issue.

**Comment by emjshrx** [comment]
> @emjshrx I've already started working on this and will open a PR by EOD today. I'll add you as a reviewer. Sorry if you already spent time on this. I forgot to mention it here that I'm working on this issue.

All good, I had just started reading up and not code yet
