### ISSUE TITLE
Add a `lookahead` for addresses

### ISSUE THREAD

**Issue by theanmolsharma** [Bitshala-Incubator/silent-pay#20]
- Generate and save 10 addresses on wallet initialization
- When generating a new address at index `i`, return address at index `i` from db. Generate and save the address at index `i + 10`
- This feature will require the following updates to wallet-db:
  - Add a key `P` to `src/wallet/db/level/layout.ts`
  - Update `saveAddress()` to store `path` (key) and `address` (value)
  - Rename `getAddress()` to `getPathFromAddress()`
  - Add a new function `getAddressFromPath()`

**Comment by emjshrx** [comment]
Does this mean we store `address:path` in `wdb.A` and `path:address` in `wdb.P`. Isnt this data duplication and if one of these is most commonly used can we just store that and if needed iterate over all db entries to get the other one?
